name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '✨ Features'
    labels: ['type: feature', 'feat']
  - title: '🐞 Fixes'
    labels: ['type: bug', 'fix', 'bug']
  - title: '⚙️ Refactor/Perf/Optimize'
    labels: ['refactor', 'perf', 'optimize']
  - title: '🧰 Chore/Build/CI'
    labels: ['chore', 'build', 'ci', 'deps']

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
change-title-escapes: '\<*_&'

header: |
  <!-- dreamapp-release-header:start -->
  ## 当前版本
  `v$RESOLVED_VERSION`

  ## 下载地址
  - macOS Apple Silicon: [点击下载](https://github.com/arnoldhao/dreamcreator/releases/download/v$RESOLVED_VERSION/dreamcreator-macos-arm64-$RESOLVED_VERSION.zip)
  - macOS Intel: [点击下载](https://github.com/arnoldhao/dreamcreator/releases/download/v$RESOLVED_VERSION/dreamcreator-macos-x64-$RESOLVED_VERSION.zip)
  - Windows 安装版: [点击下载](https://github.com/arnoldhao/dreamcreator/releases/download/v$RESOLVED_VERSION/dreamcreator-windows-x64-$RESOLVED_VERSION-installer.exe)
  - Windows 便携版: [点击下载](https://github.com/arnoldhao/dreamcreator/releases/download/v$RESOLVED_VERSION/dreamcreator-windows-x64-$RESOLVED_VERSION.zip)
  <!-- dreamapp-release-header:end -->

template: |
  $CHANGES

version-resolver:
  major: { labels: ['breaking', 'type: breaking'] }
  minor: { labels: ['type: feature', 'feat'] }
  patch: { labels: ['type: bug', 'fix', 'bug', 'chore', 'build', 'ci', 'refactor', 'perf', 'optimize', 'deps'] }
  default: patch

exclude-labels: ['skip-changelog']
