// 语义名 -> open-symbols 图标文件名（不含 .svg）
// 仅列出在应用中会用到的语义。缺啥就补。
export const ICON_MAP = {
  // 通用（优先匹配 open-symbols/lucide/symbols 下的文件名）
  search: 'search',
  open: 'square-arrow-out-up-right', // 外链/打开
  refresh: 'refresh-cw',
  settings: 'settings',
  globe: 'globe',
  database: 'database',
  clock: 'clock',
  layers: 'layers',
  folder: 'folder-open',
  'file-copy': 'copy',
  'download-cloud': 'cloud-download',
  'download-file': 'download',
  download: 'download',
  terminal: 'terminal',
  leaf: 'leaf',
  spinner: 'loader',
  close: 'x',
  plus: 'plus',
  home: 'home',
  info: 'info',
  'panel-right': 'panel-right',
  'chevron-up': 'chevron-up',
  'chevron-down': 'chevron-down',
  'search-check': 'search-check',
  'shield-check': 'shield-check',
  link: 'link',
  compass: 'compass',
  flashlight: 'flashlight',
  'arrow-left-right': 'arrow-left-right',
  wrench: 'wrench',
  video: 'video',
  image: 'image',
  trash: 'trash',
  package: 'package',
  captions: 'captions',
  languages: 'languages',
  'file-text': 'file-text',
  'file-code': 'file-code',
  'file-plus': 'file-plus',
  filter: 'filter',
  'filter-x': 'filter-x',
  sun: 'sun',
  moon: 'moon',
  heart: 'heart',
  edit: 'pencil',
  'sun-moon': 'sun-moon',
  mail: 'mail',
  github: 'github',
  twitter: 'twitter',
  play: 'play',
  'play-circle': 'play-circle',
  'panel-left-open': 'panel-left-open',
  'panel-left-close': 'panel-left-close',
  'panel-right-open': 'panel-right-open',
  'panel-right-close': 'panel-right-close',
  // document/list
  list: 'file-text',
  // 视图/查看（别名）：使用字幕图标
  view: 'captions',

  // 状态
  'status-success': 'check',
  'status-warning': 'triangle-alert',
  'status-error': 'x',
}

export const ICON_NAMES = Object.keys(ICON_MAP)
