package consts

// Subtitle AI translation prompt templates (shared by JSON/JSONL builders).
// Language placeholders should include both language code and display name to avoid ambiguity.
const (
	SubtitleJSONModeSystemPromptTpl = "You are translating subtitles from %s to %s. Keep tone consistent and adhere to the style guide. Return ONLY ONE JSON object with key 'items', whose value is an array of objects: {id, final}. No extra keys, no prose. Keep placeholders (like ⟦G000⟧, ⟦P000⟧) unchanged. When a 'glossary' array is provided in the JSON input and you see a placeholder token like ⟦G000⟧ in batch text, you MAY use the glossary entry whose 'placeholder' matches that token to understand the underlying term and keep surrounding wording and terminology consistent, BUT in your 'final' strings you MUST copy the placeholder token exactly as it appears in the input and MUST NOT replace it with the actual term or its translation. The application will substitute placeholders with the desired surface forms after your JSON is returned. If a line continues from previous, keep entity/time expressions consistent with references and boundary context."
	SubtitleJSONModeUserPrompt      = "Translate this batch with internal self-reflection. For each item: first produce a draft, briefly reflect on term consistency, tone, and errors, and then decide the final translation. However, in the actual response, only output the final translation.\nReturn ONLY ONE JSON object with field 'items', whose value is an array of objects {id,final}. Do not include intermediate drafts or reflections in the JSON."

	SubtitleJSONLSystemPromptTpl = "You are translating subtitles from %s to %s. Keep tone consistent and adhere to the style guide. Output ONLY JSON Lines: one JSON object per line with keys id and final. No code fences, no extra text. Keep placeholders (like ⟦G000⟧, ⟦P000⟧) unchanged. When a 'glossary' array is provided in the JSON input and you see a placeholder token like ⟦G000⟧ in batch text, you MAY use the glossary entry whose 'placeholder' matches that token to understand the underlying term and keep surrounding wording and terminology consistent, BUT in your 'final' strings you MUST copy the placeholder token exactly as it appears in the input and MUST NOT replace it with the actual term or its translation. The application will substitute placeholders with the desired surface forms after your JSON is returned. If a line continues from previous, keep entity/time expressions consistent with references and boundary context."
	SubtitleJSONLUserPrompt      = "Translate this batch with internal self-reflection. For each item: first produce a draft, briefly reflect on term consistency, tone, and errors, and then decide the final translation. However, in the actual response, only output the final translation.\nOutput JSONL with fields {id,final}. Do not include intermediate drafts or reflections and do not wrap with [ ] or any prose."
)
