package commands

import domaincommands "dreamcreator/internal/domain/commands"

var commandRegistry = []domaincommands.CommandDefinition{
	{
		Key:         "help",
		NativeName:  "help",
		Description: "Show available commands.",
		Scope:       domaincommands.ScopeBoth,
		Requires:    []domaincommands.CapabilityKey{domaincommands.CapabilityControlPlane},
	},
	{
		Key:         "commands",
		NativeName:  "commands",
		Description: "List all slash commands.",
		Scope:       domaincommands.ScopeBoth,
		Requires:    []domaincommands.CapabilityKey{domaincommands.CapabilityControlPlane},
	},
	{
		Key:         "skill",
		NativeName:  "skill",
		Description: "Run a skill by name.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{Name: "name", Type: "string", Required: true, Help: "Skill name"},
			{Name: "input", Type: "string", CaptureRest: true, Help: "Skill input"},
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilityRuntime},
	},
	{
		Key:         "status",
		NativeName:  "status",
		Description: "Show current status.",
		Scope:       domaincommands.ScopeBoth,
		Requires:    []domaincommands.CapabilityKey{domaincommands.CapabilityControlPlane},
	},
	{
		Key:         "allowlist",
		Description: "List/add/remove allowlist entries.",
		Scope:       domaincommands.ScopeText,
		AcceptsArgs: true,
		Requires:    []domaincommands.CapabilityKey{domaincommands.CapabilityToolPolicy},
	},
	{
		Key:         "approve",
		NativeName:  "approve",
		Description: "Approve or deny exec requests.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Requires:    []domaincommands.CapabilityKey{domaincommands.CapabilityExecApproval},
	},
	{
		Key:         "context",
		NativeName:  "context",
		Description: "Explain how context is built and used.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Requires:    []domaincommands.CapabilityKey{domaincommands.CapabilityControlPlane},
	},
	{
		Key:         "tts",
		NativeName:  "tts",
		Description: "Control text-to-speech (TTS).",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{
				Name: "action",
				Type: "string",
				Choices: []domaincommands.CommandArgChoice{
					{Value: "on", Label: "On"},
					{Value: "off", Label: "Off"},
					{Value: "status", Label: "Status"},
					{Value: "provider", Label: "Provider"},
					{Value: "limit", Label: "Limit"},
					{Value: "summary", Label: "Summary"},
					{Value: "audio", Label: "Audio"},
					{Value: "help", Label: "Help"},
				},
				Help: "TTS action",
			},
			{Name: "value", Type: "string", CaptureRest: true, Help: "Provider, limit, or text"},
		},
		ProviderOverride: map[string]string{
			"discord": "voice",
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilityVoice},
	},
	{
		Key:         "whoami",
		NativeName:  "whoami",
		Description: "Show your sender id.",
		Scope:       domaincommands.ScopeBoth,
		Requires:    []domaincommands.CapabilityKey{domaincommands.CapabilityControlPlane},
	},
	{
		Key:         "subagents",
		NativeName:  "subagents",
		Description: "List, kill, log, spawn, or steer subagent runs for this session.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{
				Name: "action",
				Type: "string",
				Choices: []domaincommands.CommandArgChoice{
					{Value: "list"},
					{Value: "kill"},
					{Value: "log"},
					{Value: "info"},
					{Value: "send"},
					{Value: "steer"},
					{Value: "spawn"},
				},
				Help: "list | kill | log | info | send | steer | spawn",
			},
			{Name: "target", Type: "string", Help: "Run id, index, or session key"},
			{Name: "value", Type: "string", CaptureRest: true, Help: "Additional input (limit/message)"},
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilitySubagents},
	},
	{
		Key:         "kill",
		NativeName:  "kill",
		Description: "Kill a running subagent (or all).",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{Name: "target", Type: "string", Help: "Label, run id, index, or all"},
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilitySubagents},
	},
	{
		Key:         "steer",
		NativeName:  "steer",
		Description: "Send guidance to a running subagent.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{Name: "target", Type: "string", Help: "Label, run id, or index"},
			{Name: "message", Type: "string", CaptureRest: true, Help: "Steering message"},
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilitySubagents},
	},
	{
		Key:         "config",
		NativeName:  "config",
		Description: "Show or set config values.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{
				Name: "action",
				Type: "string",
				Choices: []domaincommands.CommandArgChoice{
					{Value: "show"},
					{Value: "get"},
					{Value: "set"},
					{Value: "unset"},
				},
				Help: "show | get | set | unset",
			},
			{Name: "path", Type: "string", Help: "Config path"},
			{Name: "value", Type: "string", CaptureRest: true, Help: "Value for set"},
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilityControlPlane},
	},
	{
		Key:         "debug",
		NativeName:  "debug",
		Description: "Set runtime debug overrides.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{
				Name: "action",
				Type: "string",
				Choices: []domaincommands.CommandArgChoice{
					{Value: "show"},
					{Value: "reset"},
					{Value: "set"},
					{Value: "unset"},
				},
				Help: "show | reset | set | unset",
			},
			{Name: "path", Type: "string", Help: "Debug path"},
			{Name: "value", Type: "string", CaptureRest: true, Help: "Value for set"},
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilityRuntime},
	},
	{
		Key:         "usage",
		NativeName:  "usage",
		Description: "Usage footer or cost summary.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{
				Name: "mode",
				Type: "string",
				Choices: []domaincommands.CommandArgChoice{
					{Value: "off"},
					{Value: "tokens"},
					{Value: "full"},
					{Value: "cost"},
				},
				Help: "off | tokens | full | cost",
			},
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilityUsage},
	},
	{
		Key:         "stop",
		NativeName:  "stop",
		Description: "Stop the current run.",
		Scope:       domaincommands.ScopeBoth,
		Requires:    []domaincommands.CapabilityKey{domaincommands.CapabilityRuntime},
	},
	{
		Key:         "restart",
		NativeName:  "restart",
		Description: "Restart the app.",
		Scope:       domaincommands.ScopeBoth,
		Requires:    []domaincommands.CapabilityKey{domaincommands.CapabilityControlPlane},
	},
	{
		Key:         "activation",
		NativeName:  "activation",
		Description: "Set group activation mode.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{
				Name: "mode",
				Type: "string",
				Choices: []domaincommands.CommandArgChoice{
					{Value: "mention"},
					{Value: "always"},
				},
				Help: "mention | always",
			},
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilityChannels},
	},
	{
		Key:         "send",
		NativeName:  "send",
		Description: "Set send policy.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{
				Name: "mode",
				Type: "string",
				Choices: []domaincommands.CommandArgChoice{
					{Value: "on"},
					{Value: "off"},
					{Value: "inherit"},
				},
				Help: "on | off | inherit",
			},
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilityChannels},
	},
	{
		Key:         "reset",
		NativeName:  "reset",
		Description: "Reset the current session.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Requires:    []domaincommands.CapabilityKey{domaincommands.CapabilitySessionCore},
	},
	{
		Key:         "new",
		NativeName:  "new",
		Description: "Start a new session.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Requires:    []domaincommands.CapabilityKey{domaincommands.CapabilitySessionCore},
	},
	{
		Key:         "sessions",
		NativeName:  "sessions",
		Description: "List and switch session threads.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Requires:    []domaincommands.CapabilityKey{domaincommands.CapabilitySessionCore},
	},
	{
		Key:         "compact",
		NativeName:  "compact",
		Description: "Compact the session context.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{Name: "instructions", Type: "string", CaptureRest: true, Help: "Extra compaction instructions"},
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilitySessionCore},
	},
	{
		Key:         "think",
		NativeName:  "think",
		Description: "Set thinking level.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{
				Name: "level",
				Type: "string",
				Choices: []domaincommands.CommandArgChoice{
					{Value: "off"},
					{Value: "minimal"},
					{Value: "low"},
					{Value: "medium"},
					{Value: "high"},
					{Value: "xhigh"},
				},
				Help: "off | minimal | low | medium | high | xhigh",
			},
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilityRuntime},
	},
	{
		Key:         "verbose",
		NativeName:  "verbose",
		Description: "Toggle verbose mode.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{
				Name: "mode",
				Type: "string",
				Choices: []domaincommands.CommandArgChoice{
					{Value: "on"},
					{Value: "off"},
				},
				Help: "on | off",
			},
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilityRuntime},
	},
	{
		Key:         "reasoning",
		NativeName:  "reasoning",
		Description: "Toggle reasoning visibility.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{
				Name: "mode",
				Type: "string",
				Choices: []domaincommands.CommandArgChoice{
					{Value: "on"},
					{Value: "off"},
					{Value: "stream"},
				},
				Help: "on | off | stream",
			},
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilityRuntime},
	},
	{
		Key:         "elevated",
		NativeName:  "elevated",
		Description: "Toggle elevated mode.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{
				Name: "mode",
				Type: "string",
				Choices: []domaincommands.CommandArgChoice{
					{Value: "on"},
					{Value: "off"},
					{Value: "ask"},
					{Value: "full"},
				},
				Help: "on | off | ask | full",
			},
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilityExecApproval},
	},
	{
		Key:         "exec",
		NativeName:  "exec",
		Description: "Set exec defaults for this session.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{
				Name: "host",
				Type: "string",
				Choices: []domaincommands.CommandArgChoice{
					{Value: "sandbox"},
					{Value: "gateway"},
					{Value: "node"},
				},
				Help: "sandbox | gateway | node",
			},
			{
				Name: "security",
				Type: "string",
				Choices: []domaincommands.CommandArgChoice{
					{Value: "deny"},
					{Value: "allowlist"},
					{Value: "full"},
				},
				Help: "deny | allowlist | full",
			},
			{
				Name: "ask",
				Type: "string",
				Choices: []domaincommands.CommandArgChoice{
					{Value: "off"},
					{Value: "on-miss"},
					{Value: "always"},
				},
				Help: "off | on-miss | always",
			},
			{Name: "node", Type: "string", Help: "Node id or name"},
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilityExecApproval},
	},
	{
		Key:         "model",
		NativeName:  "model",
		Description: "Show or set the model.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{Name: "model", Type: "string", Help: "Model id (provider/model or id)"},
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilityModels},
	},
	{
		Key:         "models",
		NativeName:  "models",
		Description: "List model providers or provider models.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Requires:    []domaincommands.CapabilityKey{domaincommands.CapabilityModels},
	},
	{
		Key:         "queue",
		NativeName:  "queue",
		Description: "Adjust queue settings.",
		Scope:       domaincommands.ScopeBoth,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{
				Name: "mode",
				Type: "string",
				Choices: []domaincommands.CommandArgChoice{
					{Value: "steer"},
					{Value: "interrupt"},
					{Value: "followup"},
					{Value: "collect"},
					{Value: "steer-backlog"},
				},
				Help: "queue mode",
			},
			{Name: "debounce", Type: "string", Help: "debounce duration (e.g. 500ms, 2s)"},
			{Name: "cap", Type: "number", Help: "queue cap"},
			{
				Name: "drop",
				Type: "string",
				Choices: []domaincommands.CommandArgChoice{
					{Value: "old"},
					{Value: "new"},
					{Value: "summarize"},
				},
				Help: "drop policy",
			},
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilitySessionCore},
	},
	{
		Key:         "bash",
		Description: "Run host shell commands (host-only).",
		Scope:       domaincommands.ScopeText,
		AcceptsArgs: true,
		Args: []domaincommands.CommandArg{
			{Name: "command", Type: "string", CaptureRest: true, Help: "Shell command"},
		},
		Requires: []domaincommands.CapabilityKey{domaincommands.CapabilitySandbox},
	},
}
