name: Publish Release
on:
  workflow_dispatch: {}

jobs:
  publish:
    permissions:
      contents: write
      pull-requests: read
      issues: read
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          publish: true
          commitish: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
