name: Publish Release

on:
  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: write
      pull-requests: read
      issues: read
    runs-on: ubuntu-24.04
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          publish: true
          commitish: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
