name: Release macOS App

on:
  workflow_run:
    workflows: ["Publish Release"]
    types: [completed]

jobs:
  release:
    name: Release macOS App
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-latest
    permissions:
      contents: write
    env:
      TELEMETRYDECK_APP_ID: ${{ secrets.TELEMETRYDECK_APP_ID }}
      TELEMETRYDECK_ENDPOINT: ${{ secrets.TELEMETRYDECK_ENDPOINT }}
    strategy:
      matrix:
        platform:
          - darwin/amd64
          - darwin/arm64
    steps:
      - name: Resolve release metadata
        id: release_info
        uses: actions/github-script@v7
        with:
          script: |
            const run = context.payload.workflow_run;
            if (!run) {
              throw new Error('workflow_run payload is missing');
            }
            const headSha = run.head_sha;
            const {owner, repo} = context.repo;
            const tags = await github.paginate(
              github.rest.repos.listTags,
              {owner, repo, per_page: 100},
            );
            const matchedTag = tags.find(tag => tag.commit && tag.commit.sha === headSha);
            if (!matchedTag) {
              throw new Error(`找不到提交 ${headSha} 对应的 tag，请确认发布流程是否创建了 tag`);
            }
            const release = await github.rest.repos.getReleaseByTag({owner, repo, tag: matchedTag.name});
            core.info(`Resolved release tag ${release.data.tag_name} for commit ${headSha}`);
            core.setOutput('tag_name', release.data.tag_name);
            core.setOutput('version', release.data.tag_name.replace(/^v/, ''));

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.release_info.outputs.tag_name }}

      - name: Normalise platform tag
        id: normalise_platform
        shell: bash
        run: |
          tag=$(echo ${{ matrix.platform }} | sed -e 's/\//_/g' -e 's/darwin/mac/g' -e 's/amd64/intel/g')
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          # 提取架构信息用于二进制下载
          arch=$(echo ${{ matrix.platform }} | cut -d'/' -f2)
          echo "arch=$arch" >> "$GITHUB_OUTPUT"

      - name: Normalise version tag
        id: normalise_version
        shell: bash
        env:
          VERSION: ${{ steps.release_info.outputs.version }}
        run: |
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.0

      - name: Install wails
        shell: bash
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.10.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23.1.0

      # 新增：下载二进制依赖文件
      - name: Download embedded binaries
        shell: bash
        run: |
          ./scripts/fetch-embedded-binaries.sh \
            --platform "${{ matrix.platform }}" \
            --ytdlp-version "$YTDLP_VERSION" \
            --ffmpeg-version "$FFMPEG_VERSION"
          echo "Downloaded binaries:"
          ls -la backend/embedded/binaries/

      - name: Build frontend assets
        shell: bash
        run: |
          npm install -g npm@9
          jq '.info.productVersion = "${{ steps.normalise_version.outputs.version }}"' wails.json > tmp.json
          mv tmp.json wails.json
          cd frontend
          jq '.version = "${{ steps.normalise_version.outputs.version }}"' package.json > tmp.json
          mv tmp.json package.json
          npm install

      - name: Build wails app for macOS
        shell: bash
        run: |
          CGO_ENABLED=1 wails build -platform ${{ matrix.platform }} \
          -ldflags "-X dreamcreator/backend/consts.APP_VERSION=${{ steps.normalise_version.outputs.version }} -X dreamcreator/backend/consts.TelemetryAppID=${TELEMETRYDECK_APP_ID} -X dreamcreator/backend/consts.TelemetryEndpoint=${TELEMETRYDECK_ENDPOINT}"

      - name: Checkout create-image
        uses: actions/checkout@v4
        with:
          repository: create-dmg/create-dmg
          path: ./build/create-dmg
          ref: master

      - name: Build macOS DMG
        shell: bash
        working-directory: ./build
        run: |
          app_bundle=$(find bin -maxdepth 1 -type d -iname 'dreamcreator.app' | head -n1)
          if [[ -z "$app_bundle" ]]; then
            echo "DreamCreator.app not found" >&2
            exit 1
          fi
          if [[ "$app_bundle" != "bin/DreamCreator.app" ]]; then
            mv "$app_bundle" "bin/DreamCreator.app"
          fi
          ./create-dmg/create-dmg \
            --skip-jenkins \
            --no-internet-enable \
            --volname "DreamCreator" \
            --volicon "bin/DreamCreator.app/Contents/Resources/iconfile.icns" \
            --text-size 12 \
            --window-pos 400 400 \
            --window-size 660 450 \
            --icon-size 80 \
            --icon "DreamCreator.app" 180 180 \
            --hide-extension "DreamCreator.app" \
            --app-drop-link 480 180 \
            "bin/DreamCreator-${{ steps.normalise_platform.outputs.tag }}.dmg" \
            "bin"

      - name: Rename dmg
        working-directory: ./build/bin
        run: mv "DreamCreator-${{ steps.normalise_platform.outputs.tag }}.dmg" "DreamCreator_${{ steps.normalise_version.outputs.version }}_${{ steps.normalise_platform.outputs.tag }}.dmg"

      - name: Upload release asset (DMG Package)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release_info.outputs.tag_name }}
          files: ./build/bin/DreamCreator_${{ steps.normalise_version.outputs.version }}_${{ steps.normalise_platform.outputs.tag }}.dmg
          token: ${{ secrets.GITHUB_TOKEN }}
