name: semantic-pr-title
on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  check:
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
            breaking
          requireScope: false
          wip: true
